---
subtitle: "Rapport statistique V0.1"
cache: true
---


```{r}
#| label: setup

rm(list = ls())
#
library(baseph)
library(tidyverse)
library(gtsummary)
library(kableExtra)
library("forestmodel")
library(labelled)
library(epiDisplay)
library(visdat)
library(corrplot)
library(biostats)
library("colorspace")
library("apyramid")
library("FactoMineR")
library("factoextra")
library("missMDA")
library("readODS")
library("ggsci")
library("ggstats")
library("survival")
library("survminer")
#
load("datas/faceq.RData")
expx <- FALSE
classeur <- "faceq_1907v3.ods"
# if (exp){system(paste0("rm -f ",classeur))}
#
ptest <- list(all_continuous() ~ "t.test", all_categorical() ~ "chisq.test")
stt <- list(
  all_continuous() ~ "{mean} ± {sd}",
  all_categorical() ~ "{n}/{N} ({p}%)"
)
```

\bigskip


Pour toutes les variables binaire (oui/non), seul le code "`Oui`" est présenté dans la plupart des tableaux.

# Validation de la population


L'échantillon comporte `r nrow(demog)` cas dans le tableau commun mais `r nrow(pat)` patients & `r nrow(tem)` témoins dans les tableaux ad hoc. 
 
## Données manquantes

```{r}
#| label: fig-manq_demog
#| fig-cap: Données manquantes - Démographie
#| fig-asp: 1


vis_dat(demog[,c(4:16,18:28,39,40,44:51)],
         sort_type = FALSE,
          warn_large_data = FALSE) +
  labs(title = "Données manquantes - Démographie") +
    theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 70, vjust =0, hjust=0)
  )
```

```{r}
#| label: fig-manq_pat
#| fig-cap: Données manquantes - Patients
#| fig-asp: 1


vis_dat(pat[,c(3:135)],
         sort_type = FALSE,
          warn_large_data = FALSE) +
  labs(title = "Données manquantes - Patients") +
    theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 70, vjust =0, hjust=0)
  )
```

```{r}
#| label: fig-manq_tem
#| fig-cap: Données manquantes - Témoins
#| fig-asp: 1


vis_dat(tem[,c(3,4,6:96)],
         sort_type = FALSE,
          warn_large_data = FALSE) +
  labs(title = "Données manquantes - Témoins") +
    theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 70, vjust =0, hjust=0))
```

# Description de la population

```{r}
#| label: tbl-clinique
#| tbl-cap: Données cliniques

demog |> 
  dplyr::select(groupe, age:corticoides) |>
  tbl_summary(missing = "no",
              by = "groupe",
              statistic = stt,
              sort = all_categorical() ~ "frequency") |> 
   bold_labels() |> 
  add_p(test = ptest) |>
  bold_p(t = 0.05) |>
  add_overall() |> 
     modify_header(label ~ " ") |>
  pexptabph(exp = expx, nomfich = classeur , nomsheet = "demog1", lg = TRUE)
```

```{r}
#| label: tbl-tumeur
#| tbl-cap: Données tumeur

demog |> 
  dplyr::select(groupe, histo:nb_sous_unites) |>
  tbl_summary(missing = "no",
              by = "groupe",
              statistic = stt,
              sort = all_categorical() ~ "frequency") |> 
   bold_labels() |> 
  add_p(test = ptest) |>
  bold_p(t = 0.05) |>
  add_overall() |> 
     modify_header(label ~ " ") |>
  pexptabph(exp = expx, nomfich = classeur , nomsheet = "tumeur1", lg = TRUE)
```

# Réponses

## Esthétique

```{r}
#| label: prepa-esthetique

tt <- pat |> 
  dplyr::filter(moment == "J0") |>
  dplyr::select(groupe, a_symetrie_visage:i_reveil)
tp <- tem |> 
  dplyr::select(groupe, a_symetrie_visage:i_reveil)
tt <- tt |> 
  bind_rows(tp) 
```

```{r}
#| label: fig-esthetique
#| fig-cap: Échelle esthétique - Patients

tt |> dplyr::filter(groupe != "témoin") |>
  gglikert(
    a_symetrie_visage:i_reveil,
  labels_size = 3
) 
```

```{r}
#| label: fig-esthetique
#| fig-cap: Échelle esthétique - Témoins

tt |> dplyr::filter(groupe == "témoin") |>
  gglikert(
    a_symetrie_visage:i_reveil,
  labels_size = 3
) 
```

```{r}
#| label: tbl-esthetique
#| tbl-cap: Échelle esthétique 

tt |> 
  tbl_likert(include = c(a_symetrie_visage:i_reveil))

```

